version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: hiring-challenge-db
    restart: always
    volumes:
      - hiring-challenge-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 9696:3306
    cap_add:
      - SYS_NICE

  # db-shadow:
  #   image: mysql:8.0
  #   container_name: hiring-challenge-shadow-db
  #   restart: always
  #   volumes:
  #     - hiring-challenge-shadow-db-data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${SHADOW_DB_USER}
  #     MYSQL_USER: ${SHADOW_DB_USER}
  #     MYSQL_PASSWORD: ${SHADOW_DB_PASS}
  #     MYSQL_DATABASE: ${SHADOW_DB_NAME}
  #   ports:
  #     - 9697:3306
  #   depends_on:
  #     - db
  #   cap_add:
  #     - SYS_NICE

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hiring-challenge-app
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      SWAGGER_URL: ${SWAGGER_URL}
      DATABASE_URL: mysql://root:${DB_PASS}@db:3306/${DB_NAME}
      # SHADOW_DATABASE_URL: 'mysql://root:${DB_PASS}@db-shadow:9697/hiring-challenge-shadow-db'
    ports:
      - 3000:3000
    depends_on:
      - db
      # - db-shadow
    entrypoint: ['sh', '-c', 'npx prisma migrate deploy && npm run start:prod']

volumes:
  hiring-challenge-db-data:
  # hiring-challenge-shadow-db-data:
